### ISSUE TITLE
Getting this to work with jqueryui tabs

### ISSUE THREAD

**Issue by gmclelland** [jonathanstark/FastActive#1]
This is a great concept and thank you sharing your code.

I was hoping to use something like this on my jqueryui tabs.  On a mobile device, there is an delay when you tap the tab before it applies the class "ui-state-active" so the tab looks slow to become active.

I tried FastActive, but the active class doesn't get removed when you have tabs that are collapsable like in this example http://jqueryui.com/tabs/#collapsible.

The first time I click a tab, the active class is applied.  The next time I click the tab to collapse it, the active class is still applied.  So in my case the tab would stay highlighted even when it shouldn't be.

Do you know of anyway for this to work with things that need to be toggled like the collapsable tabs?

Thanks for any help you can provide?

**Comment by jonathanstark** [comment]
What you need to do is update the setActive handler to check first if the tapped element is already active. If so, just remove the class name. If not, call the clearActive function and then add the active class to the tapped element. Make sense?

**Comment by gmclelland** [comment]
Thank you for the response.  After looking into it more, it appears to be a little more complicated because in jqueryui tabs the styling is applied to the parent list item of the link as ui-state-active.
