### ISSUE TITLE
No option for selecting class name as well as tag name

### ISSUE THREAD

**Issue by mikenorthorp** [jonathanstark/FastActive#6]
Hey there, I added support for adding to an element with a certain class name instead of just a tag name

changed  if (targetTagNames.indexOf(e.target.tagName) > -1) { 

to

if (targetTagNames.indexOf(e.target.className) > -1 || targetTagNames.indexOf(e.target.tagName) > -1) {

Just a quick little fix that may be useful to others, your script was very helpful!

**Comment by jonathanstark** [comment]
Thanks for the feedback! I'm glad you found FastActive useful. I'm considering adding support for arbitrary selectors but I'm not yet convinced it can be in a way that is generic, compact, and self-explanatory. But I haven't given up so stay tuned :)

**Comment by jonathanstark** [comment]
FYI - I added support for arbitrary conditional logic:

https://github.com/jonathanstark/FastActive/commit/7a74dd0c9a70f4a15160971f93e7a686ff332830

**Comment by mikenorthorp** [comment]
Awesome stuff!
